#!/bin/bash
iso=$1
usb=$2
if [ -z "$iso" ];
then
	read -p "Write path to iso file: " iso
fi

if [ -z "$usb" ];
then
	read -p "Write path to disk: " usb
fi

dd bs=4M if=$iso of=$usb
echo "iso2usb complete"
